### PR TITLE
DIR-889 postponed review fixes

### PR DESCRIPTION
**Pull request by sebxian**

### CODE REVIEW

**Review by stefan-kracht — APPROVED** [review]
Very good suggestions, thank you!

**Comment by stefan-kracht** [comment]
FYI: The `develop` branch is being discontinued, and we're transitioning to use the `main` branch. I've recently merged the latest changes from `develop` into `main` and adjusted the target of this pull request from `develop` to `main`. Since both branches share the same head, this shouldn't have any impact.

**Comment by sebxian** [comment]
@stefan-kracht I found this old PR, we probably forgot it when I got sick. I merged main into this and reviewed my changes, I think they are still valid and we can merge them.

It's mainly spelling fixes but it also fixes two buttons that don't work currently (they link to the docs from the API commands and JQ playground pages).

**Review by stefan-kracht — DISMISSED** [review]
Yes, I think this can be merged. I just ran all the test successfully.

**Pull request merged**
